# Generated by Django 6.0.2 on 2026-03-29 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
