# Generated by Django 6.0.2 on 2026-06-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_apirequestlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='monitoring__endpoin_634a1d_idx',
            old_name='monitoring_endpoint_91a9d0_idx',
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='source',
            field=models.CharField(default='external', max_length=50),
        ),
    ]
